export const ADD_CART = 'ADD_CART';
export const HANDLE_QUANTITY = 'HANDLE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_CATEGORIES = 'GET_CATEGORIES';

